### ISSUE TITLE
Invalid Oauth2 redirect_uri

### ISSUE THREAD

**Issue by hugoxx-official** [TunaSayin/verification-bot#1]
Why appears this error: Invalid Oauth2 redirect_uri
How can i solve it?

**Comment by tunasayin** [comment]
It looks like the redirect URI in the config file is not included in the your app's redirect URI list. You have to add the redirect URI to your app's redirect URI list.

![image](https://user-images.githubusercontent.com/65562418/187072656-f3f000b8-7e85-4aff-a681-a9b19a0dd5ee.png)
